### ISSUE TITLE
What are parameters in the function?

### ISSUE THREAD

**Issue by epogrebnyak** [open-risk/portfolio_analytics_library#1]
Perhaps there is a web page that describes the function?

https://github.com/open-risk/portfolioAnalytics/blob/c9a086fec0839e871146ce2becca29fd0763096e/portfolioAnalytics/vasicek.py#L25-L33

**Comment by epogrebnyak** [comment]
```
""" Using the portfolio model library to calculate default probabilities in finite 
portfolio with N credits - Calculate probability of k losses
"""

# Calculate the probability of four losses in a portfolio of ten credits when the PD is 0.1 and correlation is 20%

print("p=", vasicek_base(10, 0, 0.34140, 0.2))
```
Following the above `N` is numer of exposures, `rho` is correlation, but what are `k` and `p`?

`p` seems to be a probability of default and `k` seems a number of defaults?

**Comment by open-risk** [comment]
Your guess is correct. I have pushed a version with improved documentation. Please take a look and if there are other questions happy to clarify. More mathematical documentation / references coming [here](https://www.openriskmanual.org/wiki/Vasicek_Distribution)

**Comment by epogrebnyak** [comment]
Thanks so much, will review!

пн, 23 мар. 2020 г., 20:54 Open Risk <notifications@github.com>:
