### ISSUE TITLE
unable to find portfolioAnalytics package on pyPI

### ISSUE THREAD

**Issue by 1rdsk1** [open-risk/portfolio_analytics_library#3]
Hi

I would like to install the portfolioAnalytics package in an Anaconda environment but cannot find the package.  

(vasicek) C:\Users\ruper>pip3 install portfolioAnalytics
ERROR: Could not find a version that satisfies the requirement portfolioAnalytics (from versions: none)
ERROR: No matching distribution found for portfolioAnalytics

I also tried to find it on pyPI.org but it could not find it there.

I see that the last update of the the portfolioAnalytics package was in 2019 but the readme file says its still underdevelopment.

Please what remains to be done and is further development planned?

**Comment by open-risk** [comment]
Good point, a PyPI release is overdue... will need some further cleaning and testing.

As for further work, there is a todo file that lists some ideas for expanding the library. Suggestions and/or contributions are welcome!

**Comment by 1rdsk1** [comment]
Thanks.  Please do you have a timescale for putting it on pyPI?  I'd like to try it out asap.  Can I download the package an install it locally?

**Comment by open-risk** [comment]
If you clone it locally you should be able to import any of the basic functions and work with it for the time being. Will try to get around it within a few days. NB: For some of the examples there is a dependency on another library [transitionMatrix](https://github.com/open-risk/transitionMatrix). The two used to be one larger package. transitionMatrix is already on PyPI.

Are you interested in the single period or the multiperiod case?  The later is implemented in the thresholds subdirectory and is quite a bit more [complex](https://www.openriskmanual.org/wiki/Threshold_Models)

**Comment by 1rdsk1** [comment]
Hi, 

Probably single period to start with but later on possibly will try the multiperiod i fI get ti to work.

I tried to install locally but get error that 'portfolioAnalytics\estimators' does not exist per below:

(vasicek) C:\Users\ruper>pip install git+git://github.com/open-risk/portfolioAnalytics.git
Collecting git+git://github.com/open-risk/portfolioAnalytics.git
  Cloning git://github.com/open-risk/portfolioAnalytics.git to c:\users\ruper\appdata\local\temp\pip-req-build-706assng
  Running command git clone --filter=blob:none --quiet git://github.com/open-risk/portfolioAnalytics.git 'C:\Users\ruper\AppData\Local\Temp\pip-req-build-706assng'
  Resolved git://github.com/open-risk/portfolioAnalytics.git to commit 19453e4dae48cd260a045081909dfcac9adbe451
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      running egg_info
      creating C:\Users\ruper\AppData\Local\Temp\pip-pip-egg-info-arh8vguu\portfolioAnalytics.egg-info
      writing C:\Users\ruper\AppData\Local\Temp\pip-pip-egg-info-arh8vguu\portfolioAnalytics.egg-info\PKG-INFO
      writing dependency_links to C:\Users\ruper\AppData\Local\Temp\pip-pip-egg-info-arh8vguu\portfolioAnalytics.egg-info\dependency_links.txt
      writing requirements to C:\Users\ruper\AppData\Local\Temp\pip-pip-egg-info-arh8vguu\portfolioAnalytics.egg-info\requires.txt
      writing top-level names to C:\Users\ruper\AppData\Local\Temp\pip-pip-egg-info-arh8vguu\portfolioAnalytics.egg-info\top_level.txt
      writing manifest file 'C:\Users\ruper\AppData\Local\Temp\pip-pip-egg-info-arh8vguu\portfolioAnalytics.egg-info\SOURCES.txt'
      error: package directory 'portfolioAnalytics\estimators' does not exist
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by open-risk** [comment]
yes that is a leftover in the setup file from the transition matrix estimator functionality that is now done separately. will aim to fix.

**Comment by 1rdsk1** [comment]
Thanks.  I am struggling to understand the integration performed in the vasciek base module:
N=10
k=0
p=0.34140 #why this value?
rho=0.2
...
    arg = (a - rho * z) / math.sqrt(1 - rho * rho)
    phi_den = stats.norm.pdf(z, loc=0.0, scale=1.0)
    phi_cum = stats.norm.cdf(arg, loc=0.0, scale=1.0)
    integrant = phi_den * math.pow(phi_cum, k) * math.pow(1 - phi_cum, N - k) * binomial(N, k)
Please could you help?

**Comment by open-risk** [comment]
Those N,k,p,rho values are just a random selection of values from the example. You can change them to any value that makes sense.

Do you also mean to understand the integration formulas? More detailed documentation / references or some educational walk-through is still lacking. The general type of integration berformed for the default threshold calculation (these _a_ variables) is as per the [single period](https://www.openriskmanual.org/wiki/Threshold_Models) segment and the rest is combinatorial summation. As this is not so much code related maybe a better place to discuss those things is [here](https://www.openriskcommons.org/t/portfolioanalytics-documentation/89). It is a forum to discuss all the projects, also from the user perspective. It is not very active yet but in the long run it should be more convenient aggregator for this type of question.

As promised I will try to have a more cleaned up release soon :-)

**Comment by open-risk** [comment]
**portfolioAnalytics** is now on [PyPI](https://pypi.org/project/creditPortfolioAnalytics/). There was a name conflict with a old package so the PyPI name for the library is creditPortfolioAnalytics. It still an alpha release, please raise an issue if some file is missing or if the tests / examples do not run in your system. 

There is also [online documentation](https://portfolioanalytics.readthedocs.io/en/latest/) of the code (still incomplete, needs updating / cleaning up). For any usage questions the [Commons](https://www.openriskcommons.org/c/open-source/portfolioanalytics/18) is best.
