### ISSUE TITLE
Definition of rho in vasicek

### ISSUE THREAD

**Issue by gig67** [open-risk/portfolio_analytics_library#6]
Many thanks for this helpful package, saves a lot of time. 
I just think that in vasicek.py, the input parameter rho seems at odds with the definitions in "THE DISTRIBUTION OF LOAN PORTFOLIO VALUE" by Vasicek (2002) equation (5) and with the formulae in BIS "An Explanatory Note on the Basel II IRB Risk Weight Functions".
I think where you write rho**2 you should have just rho, and where you write rho it should be np.sqrt(rho).
For example in vasicek_lim, where you write
arg2 = (math.sqrt(1 - rho * rho) * arg1 - a1) / rho
I think it should be instead
arg2 = (math.sqrt(1 - rho) * arg1 - a1) / np.sqrt(rho)

**Comment by open-risk** [comment]
Thanks for the comment. Yes, the use of rho as parameter was confusing. Now switched to use "beta" for the sqrt(rho). The functions API remains the same, i.e. the input is supposed to be the asset correlation.
